Backend configuration with support tools
UniversityOfGdanskTeamPython/epseon_gui pull request #24
Opened 2023-11-15 19:09 UTC by mateuszzalewski011

2023-11-16 00:45 UTC, Argmaster commented on .github/ISSUE_TEMPLATE/functiona_feature_request.md
> +name: Syntax feature request
```suggestion
name: Feature request
```

2023-11-16 00:46 UTC, Argmaster commented on .github/ISSUE_TEMPLATE/functiona_feature_request.md
> +
```suggestion

```

2023-11-16 00:46 UTC, Argmaster commented on .github/ISSUE_TEMPLATE/functiona_feature_request.md
> +
```suggestion
```

2023-11-16 01:00 UTC, Argmaster requested changes

2023-11-16 01:00 UTC, Argmaster commented on test/__init__.py
> +"""PEC Framework test suite root."""
```suggestion
"""Epseon GUI test suite root."""
```

2023-11-16 01:01 UTC, Argmaster commented
I'd be great to have those fixed before next meeting, maybe even merged before.

2023-11-16 18:59 UTC, Ave44 approved these changes

2023-11-16 18:59 UTC, Ave44 commented on .dockerignore
> +Dockerfile*
If we'll change name of our dockerfiles then we should add rule `*.dockerfile`

2023-11-19 14:29 UTC, Argmaster commented on .github/ISSUE_TEMPLATE/functiona_feature_request.md
> +name: Feature request about: Request new functional feature. title: "" labels:
You have messed up header structure.

2023-11-20 01:23 UTC, Argmaster commented on .pre-commit-config.yaml
> +      rev: "v2.7.1"
@mateuszzalewski011 please change this to `v3.0.3`

2023-11-21 01:00 UTC, Argmaster commented on .pre-commit-config.yaml
> +      rev: "v2.7.1"
Okay, but it still shows as `v2.7.1` in review, am I missing something?

2023-11-26 02:11 UTC, Argmaster commented
Any chance to get this merged? I am still waiting for response on Prettier version.

2023-11-26 17:22 UTC, Ave44 commented on .pre-commit-config.yaml
> +      rev: "v2.7.1"
version updated

2023-11-26 17:24 UTC, Ave44 submitted a review, later dismissed

2023-11-26 17:48 UTC, Argmaster submitted a review, later dismissed

2023-11-26 17:51 UTC, Argmaster approved these changes

2023-11-26 17:52 UTC, Ave44 approved these changes

2023-11-26 17:53 UTC, merged